apiVersion: v1
kind: Service
metadata:
  name: mcp-k8s-networking
  namespace: mcp-k8s-networking
  labels:
    app: mcp-k8s-networking
spec:
  type: ClusterIP
  selector:
    app: mcp-k8s-networking
  ports:
    - port: 8080
      targetPort: mcp
      name: mcp
      protocol: TCP
