apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-k8s-networking.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-k8s-networking.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "mcp-k8s-networking.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mcp
      name: mcp
      protocol: TCP
